from django import forms
from django.forms import ComboField

class ExportForm(forms.Form):
	CHOICES = (('','All',),('01', 'Culture et production animale, chasse et services annexes',),
	('02', 'Sylviculture et exploitation forestière',),
	('03', 'Pêche et aquaculture',),
	('05', 'Extraction de houille et de lignite',),
	('06', 'Extraction d''hydrocarbures',),
	('07', 'Extraction de minerais métalliques',),
	('08', 'Autres industries extractives',),
	('09', 'Services de soutien aux industries extractives',),
	('10', 'Industries alimentaires',),
	('11', 'Fabrication de boissons',),
	('12', 'Fabrication de produits à base de tabac',),
	('13', 'Fabrication de textiles',),
	('14', 'Industrie de l''habillement',),
	('15', 'Industrie du cuir et de la chaussure',),
	('16', 'Travail du bois et fabrication d''articles en bois et en liège',),
	('17', 'Industrie du papier et du carton',),
	('18', 'Imprimerie et reproduction d''enregistrements',),
	('19', 'Cokéfaction et raffinage',),
	('20', 'Industrie chimique',),
	('21', 'Industrie pharmaceutique',),
	('22', 'Fabrication de produits en caoutchouc et en plastique',),
	('23', 'Fabrication d''autres produits minéraux non métalliques',),
	('24', 'Métallurgie',),
	('25', 'Fabrication de produits métalliques, à l’exception des machines et des équipements',),
	('26', 'Fabrication de produits informatiques, électroniques et optiques',),
	('27', 'Fabrication d''équipements électriques',),
	('28', 'Fabrication de machines et équipements n.c.a.',),
	('29', 'Industrie automobile',),
	('30', 'Fabrication d''autres matériels de transport',),
	('31', 'Fabrication de meubles',),
	('32', 'Autres industries manufacturières',),
	('33', 'Réparation et installation de machines et d''équipements',),
	('35', 'Production et distribution d''électricité, de gaz, de vapeur et d''air conditionné',),
	('36', 'Captage, traitement et distribution d''eau ',),
	('37', 'Collecte et traitement des eaux usées',),
	('38', 'Collecte, traitement et élimination des déchets ; récupération',),
	('39', 'Dépollution et autres services de gestion des déchets',),
	('41', 'Construction de bâtiments',),
	('42', 'Génie civil',),
	('43', 'Travaux de construction spécialisés ',),
	('45', 'Commerce et réparation d''automobiles et de motocycles',),
	('46', 'Commerce de gros, à l’exception des automobiles et des motocycles',),
	('47', 'Commerce de détail, à l’exception des automobiles et des motocycles',),
	('49', 'Transports terrestres et transport par conduites',),
	('50', 'Transports par eau',),
	('51', 'Transports aériens',),
	('52', 'Entreposage et services auxiliaires des transports',),
	('53', 'Activités de poste et de courrier',),
	('55', 'Hébergement',),
	('56', 'Restauration',),
	('58', 'Édition',),
	('59', 'Production de films cinématographiques, de vidéo et de programmes de télévision ; enregistrement sonore et édition musicale',),
	('60', 'Programmation et diffusion',),
	('61', 'Télécommunications',),
	('62', 'Programmation, conseil et autres activités informatiques ',),
	('63', 'Services d''information',),
	('64', 'Activités des services financiers, hors assurance et caisses de retraite',),
	('65', 'Assurance',),
	('66', 'Activités auxiliaires de services financiers et d''assurance ',),
	('68', 'Activités immobilières',),
	('69', 'Activités juridiques et comptables',),
	('70', 'Activités des sièges sociaux ; conseil de gestion',),
	('71', 'Activités d''architecture et d''ingénierie ; activités de contrôle et analyses techniques',),
	('72', 'Recherche-développement scientifique',),
	('73', 'Publicité et études de marché',),
	('74', 'Autres activités spécialisées, scientifiques et techniques',),
	('75', 'Activités vétérinaires',),
	('77', 'Activités de location et location-bail',),
	('78', 'Activités liées à l''emploi',),
	('79', 'Activités des agences de voyage, voyagistes, services de réservation et activités connexes',),
	('80', 'Enquêtes et sécurité',),
	('81', 'Services relatifs aux bâtiments et aménagement paysager',),
	('82', 'Activités administratives et autres activités de soutien aux entreprises',),
	('84', 'Administration publique et défense ; sécurité sociale obligatoire',),
	('85', 'Enseignement',),
	('86', 'Activités pour la santé humaine',),
	('87', 'Hébergement médico-social et social',),
	('88', 'Action sociale sans hébergement',),
	('90', 'Activités créatives, artistiques et de spectacle',),
	('91', 'Bibliothèques, archives, musées et autres activités culturelles',),
	('92', 'Organisation de jeux de hasard et d''argent',),
	('93', 'Activités sportives, récréatives et de loisirs',),
	('94', 'Activités des organisations associatives',),
	('95', 'Réparation d''ordinateurs et de biens personnels et domestiques',),
	('96', 'Autres services personnels',),
	('97', 'Activités des ménages en tant qu''employeurs de personnel domestique',),
	('98', 'Activités indifférenciées des ménages en tant que producteurs de biens et services pour usage propre',),
	('99', 'Activités des organisations et organismes extraterritoriaux',),)
	code_activite = forms.ChoiceField(widget=forms.Select, choices=CHOICES,required=False)
	CHOICES2 = (('', 'All',),('75', 'Paris',), ('01', '01 - Ain',),
	('02', '02 - Aisne',),('03', '03 - Allier',),('04', '04 - Alpes-de-Haute-Provence',),('05', '05 - Hautes-alpes',),
	('06', '06 - Alpes-maritimes',),('07', '07 - Ardèche',),('08', '08 - Ardennes',),('09', '09 - Ariège',),
	('10', '10 - Aube',),('11', '11 - Aude',),('12', '12 - Aveyron',),
	('13', '13 - Bouches-du-Rhône',),('14', '14 - Calvados',),('15', '15 - Cantal',),
	('16', '16 - Charente',),('17', '17 - Charente-maritime',),('18', '18 - Cher',),
	('19', '19 - Corrèze',),('2a', '2a - Corse-du-sud',),('2b', '2b - Haute-Corse',),
	('21', '21 - Côte-d Or',),('22', '22 - Côtes-d Armor',),('23', '23 - Creuse',),
	('24', '24 - Dordogne',),('25', '25 - Doubs',),('26', '26 - Drôme',),
	('27', '27 - Eure',),('28', '28 - Eure-et-loir',),('29', '29 - Finistère',),
	('30', '30 - Gard',),('31', '31 - Haute-garonne',),('32', '32 - Gers',),('33', '33 - Gironde',),
	('34', '34 - Hérault',),('35', '35 - Ille-et-vilaine',),('36', '36 - Indre',),('37', '37 - Indre-et-loire',),
	('38', '38 - Isère',),('39', '39 - Jura',),('40', '40 - Landes',),('41', '41 - Loir-et-cher',),
	('42', '42 - Loire',),('43', '43 - Haute-loire',),('44', '44 - Loire-atlantique',),('45', '45 - Loiret',),
	('46', '46 - Lot',),('47', '47 - Lot-et-garonne',),('48', '48 - Lozère',),('49', '49 - Maine-et-loire',),
	('50', '50 - Manche',),('51', '51 - Marne',),('52', '52 - Haute-marne',),('53', '53 - Mayenne',),
	('54', '54 - Meurthe-et-moselle',),('55', '55 - Meuse',),('56', '56 - Morbihan',),('57', '57 - Moselle',),
	('58', '58 - Nièvre',),('59', '59 - Nord',),('60', '60 - Oise',),('61', '61 - Orne',),
	('62', '62 - Pas-de-calais',),('63', '63 - Puy-de-dôme',),('64', '64 - Pyrénées-atlantiques',),('65', '65 - Hautes-Pyrénées',),
	('66', '66 - Pyrénées-orientales',),('67', '67 - Bas-rhin',),('68', '68 - Haut-rhin',),('69', '69 - Rhône',),
	('70', '70 - Haute-saône ',),('71', '71 - Saône-et-loire',),('72', '72 - Sarthe',),('73', '73 - Savoie',),
	('74', '74 - Haute-savoie',),('76', '76 - Seine-maritime',),('77', '77 - Seine-et-marne',),
	('78', '78 - Yvelines',),('79', '79 - Deux-sèvres',),('80', '80 - Somme',),('81', '81 - Tarn',),
	('82', '82 - Tarn-et-garonne',),('83', '83 - Var',),('84', '84 - Vaucluse',),('85', '85 - Vendée',),('86', '86 - Vienne',),
	('87', '87 - Haute-vienne',),('88', '88 - Vosges',),('89', '89 - Yonne',),('90', '90 - Territoire de belfort',),('91', '91 - Essonne',),
	('92', '92 - Hauts-de-seine',),('93', '93 - Seine-Saint-Denis',),('94', '94 - Val-de-marne',),('95', '95 - Val-d''oise',),('971', '971 - Guadeloupe',),
	('972', '972 - Martinique',),('973', '973 - Guyane',),('974', '974 - La réunion',),('976', '976 - Mayotte',),)
	code_postale = forms.ChoiceField(widget=forms.Select, choices=CHOICES2,required=False)
	siren = forms.CharField(max_length=100,required=False)
	nom = forms.CharField(max_length=100,required=False)
	path = forms.CharField(max_length=1000,required=False)