# -*- coding: utf-8 -*-
"""
Created on Sun Apr 22 20:28:11 2018

@author: Guillaume
"""
class Code_liasse():
    code_liasse_actif_complet = {
        'AA':'Capital souscrit non appelé',
        'AB':'Frais d’établissement',
        'CX':'Frais de développement ou de recherche et développement',
        'AF':'Concessions, brevets et droits similaires',
        'AH':'Fonds commercial',
        'AJ':'Autres immobilisations incorporelles',
        'AL':'Avances et acomptes sur immobilisations incorporelles.',
        'AN':'Terrains',
        'AP':'Constructions',
        'AR':'Installations techniques, matériel et outillage industriels',
        'AT':'Autres immobilisations corporelles',
        'AV':'Immobilisations en cours',
        'AX':'Avances et acomptes',
        'CS':'Participations évaluées - mise en équivalence',
        'CU':'Autres participations',
        'BB':'Créances rattachées à des participations',
        'BD':'Autres titres immobilisés',
        'BF':'Prêts',
        'BH':'Autres immobilisations financières',
        'BJ':'TOTAL (I)',
        'BL':'Matières premières, approvisionnements',
        'BN':'En cours de production de biens',
        'BP':'En cours de production de services',
        'BR':'Produits intermédiaires et finis',
        'BT':'Marchandises',
        'BV':'Avances et acomptes versés sur commandes',
        'BX':'Clients et comptes rattachés',
        'BZ':'Autres créances',
        'CB':'Capital souscrit et appelé, non versé',
        'CD':'Valeurs mobilières de placement',
        'CF':'Disponibilités',
        'CH':'Charges constatées d’avance',
        'CJ':'TOTAL (II)',
        'CW':'Charges à répartir ou frais d’émission d’emprunt',
        'CM':'Primes de remboursement des obligations (IV)',
        'CN':'Ecarts de conversion actif (V)',
        'CO':'TOTAL GENERAL (0 à V)',
        'CP':'Parts à moins d’un an',
        'CR':'Parts à plus d’un an'
            
        }

    code_liasse_passif_complet = {
        'DA':'Capital social ou individuel',
        'DB':'Primes d’émission, de fusion, d’apport, ...',
        'EK':'(dont écart d’équivalence)',
        'DC':'Ecarts de réévaluation',
        'DD':'Réserve légale (1)',
        'DE':'Réserves statutaires ou contractuelles',
        'B1':'(dont réserve spéciale des provisions pour fluctuation des cours)',
        'DF':'Réserves réglementées (1)',
        'EJ':'(dont réserve relative à l’achat d’œuvres originales d’artistes vivants)',
        'DG':'Autres réserves',
        'DH':'Report à nouveau',
        'DI':'RESULTAT DE L’EXERCICE (bénéfice ou perte)',
        'DJ':'Subventions d’investissement',
        'DK':'Provisions réglementées',
        'DL':'TOTAL (I)',
        'DM':'Produit des émissions de titres participatifs',
        'DN':'Avances conditionnées',
        'DO':'TOTAL (II)',
        'DP':'Provisions pour risques',
        'DQ':'Provisions pour charges',
        'DR':'TOTAL (III)',
        'DS':'Emprunts obligataires convertibles',
        'DT':'Autres emprunts obligataires',
        'DU':'Emprunts et dettes auprès des établissements de crédit (3)',
        'DV':'Emprunts et dettes financières divers (4)',
        'DW':'Avances et acomptes reçus sur commandes en cours',
        'DX':'Dettes fournisseurs et comptes rattachés',
        'DY':'Dettes fiscales et sociales',
        'DZ':'Dettes sur immobilisations et comptes rattachés',
        'EA':'Autres dettes',
        'EB':'Produits constatés d’avance (2)',
        'EC':'TOTAL (IV)',
        'ED':'(V)',
        'EE':'TOTAL GENERAL (I à V)',
        'EF':'Dont réserve réglementée des plus-values à long terme',
        'EG':'Dettes et produits constatés d’avance à moins d’un an',
        'EH':'Dont concours bancaires courants, et soldes créditeurs de banques et C.C.P.',
        'EI':'Dont emprunts participatifs',
        }


    code_liasse_CR_complet = {
        'FA':'Ventes de marchandises',
        'FD':'Production vendue biens',
        'FG':'Production vendue services',
        'FJ':'Chiffres d’affaires nets',
        'FM':'Production stockée',
        'FN':'Production immobilisée',
        'FO':'Subventions d’exploitation',
        'FP':'Reprises sur amortissements et provisions, transfert de charges',
        'FQ':'Autres produits',
        'FR':'Total des produits d’exploitation (I)',
        'FS':'Achats de marchandises (y compris droits de douane)',
        'FT':'Variation de stock (marchandises)',
        'FU':'Achats de matières premières et autres approvisionnements',
        'FV':'Variation de stock (matières premières et approvisionnements)',
        'FW':'Autres achats et charges externes',
        'FX':'Impôts, taxes et versements assimilés',
        'FY':'Salaires et traitements',
        'FZ':'Charges sociales',
        'GA':'Dot. d’exploit. - Dotations aux amortissements',
        'GB':'Dot. d’exploit. - Dotations aux provisions',
        'GC':'Dot. d’exploit. Sur actif circulant : dotations aux provisions',
        'GD':'Dot. d’exploit. Pour risques et charges : dotations aux provisions',
        'GE':'Autres charges',
        'GF':'Total des charges d’exploitation (II)',
        'GG':'- RESULTAT D’EXPLOITATION (I - II)',
        'GH':'Bénéfice attribué ou perte transférée',
        'GI':'Perte supportée ou bénéfice transféré',
        'GJ':'Produits financiers de participations',
        'GK':'Produits des autres valeurs mobilières et créances de l’actif immobilisé',
        'GL':'Autres intérêts et produits assimilés',
        'GM':'Reprises sur provisions et transferts de charges',
        'GN':'Différences positives de change',
        'GO':'Produits nets sur cessions de valeurs mobilières de placement',
        'GP':'Total des produits financiers (V)',
        'GQ':'Dotations financières sur amortissements et provisions',
        'GR':'Intérêts et charges assimilées',
        'GS':'Différences négatives de change',
        'GT':'Charges nettes sur cessions de valeurs mobilières de placement',
        'GU':'Total des charges financières (VI)',
        'GV':'- RESULTAT FINANCIER (V - VI)',
        'GW':'RESULTAT COURANT AVANT IMPOTS (I - II + III - IV + V - VI)',
        'HA':'Produits exceptionnels sur opérations de gestion',
        'HB':'Produits exceptionnels sur opérations en capital',
        'HC':'Reprises sur provisions et transferts de charges',
        'HD':'Total des produits exceptionnels (VII)',
        'HE':'Charges exceptionnelles sur opérations de gestion',
        'HF':'Charges exceptionnelles sur opérations en capital',
        'HG':'Dotations exceptionnelles aux amortissements et provisions',
        'HH':'Total des charges exceptionnelles (VIII)',
        'HI':'- RESULTAT EXCEPTIONNEL (VII - VIII)',
        'HJ':'Participation des salariés aux résultats de l’entreprise',
        'HK':'Impôts sur les bénéfices (X)',
        'HL':'TOTAL DES PRODUITS (I + III + V +VII)',
        'HM':'TOTAL DES CHARGES (II + IV + VI + VIII + IX + X)',
        'HN':'BENEFICE OU PERTE (Total des produits - Total des charges)',
        'HP':'Renvois : Crédit-bail mobilier',
        'HQ':'Renvois : Crédit-bail immobilier',
        'A1':'Renvois : Transfert de charges',
        'A2':'Renvois : Cotisations personnelles de l’exploitant',
        'A3':'Renvois : Redevances pour concessions de brevets, de licences (produits)',
        'A4':'Renvois : Redevances pour concessions de brevets, de licences (charges)'
        }

    code_liasse_Immo_complet = {
        'CZ':'ACQUISITIONS Frais d’établissement, et de développement ou de recherche',
        'KD':'ACQUISITIONS Total dont autres postes d’immobilisations incorporelles',
        'LN':'ACQUISITIONS Total Immobilisations corporelles',
        'LQ':'ACQUISITIONS Total Immobilisations financières',
        'OG':'ACQUISITIONS Total Général',
        'IN':'DIMINUTIONS Frais d’établissement, et de développement ou de recherche',
        'IO':'DIMINUTIONS Total dont autres postes d’immobilisations incorporelles',
        'MY':'DIMINUTIONS Virement postes immobilisations corporelles en cours',
        'NC':'DIMINUTIONS Virement postes - Avances et acomptes',
        'IY':'DIMINUTIONS Total Immobilisations corporelles',
        'I2':'DIMINUTIONS Prêts et immobilisations financières',
        'I3':'DIMINUTIONS Total Immobilisations financières',
        'I4':'DIMINUTIONS Total Général'
        }


    code_liasse_Ammo_complet = {
        'CY':'AMORTISSEMENTS Frais d’établissement, et de développement ou de recherche',
        'PE':'AMORTISSEMENTS Total dont autres immobilisations incorporelles',
        'QU':'AMORTISSEMENTS Total Immobilisations corporelles',
        'ON':'AMORTISSEMENTS Total Général',
        'Z9':'Charges à répartir ou frais d’émission d’emprunt',
        'SP':'mvt. sur charges rép. - Primes de remboursement des obligations'
        }


    code_liasse_Provision_complet = {
        '3X':'Amortissements dérogatoires',
        '3Z':'Total Provisions réglementées',
        '4A':'Provisions pour litiges',
        '4E':'Provisions pour garanties données aux clients',
        '4J':'Provisions pour perte sur marchés à terme',
        '4N':'Provisions pour amendes et pénalités',
        '4T':'Provisions pour perte de change',
        '4X':'Provisions pour pensions et obligations similaires',
        '5B':'Provisions pour impôts',
        '5F':'Provisions pour renouvellement des immobilisations',
        'EO':'Provisions pour gros entretien et grandes révisions ou grosses réparations',
        '5R':'Provisions pour charges sociales et fiscales sur congés à payer',
        '5V':'Autres provisions pour risques et charges',
        '5Z':'Total Provisions pour risques et charges',
        '6A':'sur immobilisations – incorporelles',
        '6E':'sur immobilisations – corporelles',
        '02':'sur immobilisations – titres mis en équivalence',
        '9U':'sur immobilisations – titres de participation',
        '06':'sur immobilisations –autres immobilisations financières',
        '6N':'Sur stocks et en cours',
        '6T':'Sur comptes clients',
        '6X':'Autres provisions pour dépréciation',
        '7B':'Total Provisions pour dépréciation',
        '7C':'TOTAL GENERAL',
        'UE':'dont dotations et reprises : - d’Exploitation',
        'UG':'dont dotations et reprises :- Financières',
        'UJ':'dont dotations et reprises :- Exceptionnelles',
        }

    code_liasse_Provision_complet = {
        'UL':'Créances rattachées à des participations',
        'UP':'Prêts',
        'UT':'Autres immobilisations financières',
        'VA':'Clients douteux ou litigieux',
        'UX':'Autres créances clients',
        'UO':'(provision pour dépréciation antérieurement constituée)',
        'Z1':'Créances représentatives de titres prêtés',
        'UY':'Personnel et comptes rattachés',
        'UZ':'Sécurité Sociale, autres organismes sociaux',
        'VM':'Impôts sur les bénéfices',
        'VB':'T. V. A.',
        'VN':'Autres impôts, taxes versements assimilés',
        'VP':'Divers',
        'VC':'Groupe et associés',
        'VR':'Débiteurs divers (dont créances relatives à des opérations de pension de titres)',
        'VS':'Charges constatées d’avance',
        'VT':'TOTAL – ETAT DES CREANCES',
        '7Y':'Emprunts obligataires convertibles brut à un an au plus',
        '7Z':'Autres emprunts obligataires brut à un an au plus',
        'VG':'Emprunts à 1 an maximum à l’origine',
        'VH':'Emprunts à plus d’1 an à l’origine',
        '8A':'Emprunts et dettes financières divers',
        '8B':'Fournisseurs et comptes rattachés',
        '8C':'Personnel et comptes rattachés',
        '8D':'Sécurité sociale et autres organismes sociaux',
        '8E':'Impôts sur les bénéfices',
        'VW':'T.V.A.',
        'VX':'Obligations cautionnées',
        'VQ':'Autres impôts, taxes et assimilés',
        '8J':'Dettes sur immobilisations et comptes rattachés',
        'VI':'Groupe et associés',
        '8K':'Autres dettes (dont dettes relatives à des opérations de pension de titre)',
        'Z2':'Dette représentative de titres empruntés',
        '8L':'Produits constatés d’avance',
        'VY':'TOTAL – ETAT DES DETTES',
        'VJ':'Emprunts souscrits en cours d’exercice',
        'VK':'Emprunts remboursés en cours d’exercice'
        }


    code_liasse_AffecRes_complet = {
        'ZE':'Dividendes',
        'YQ':'Engagement de crédit-bail mobilier',
        'YR':'Engagement de crédit-bail immobilier',
        'YS':'Effets portés à l’escompte et non échus',
        'YT':'Sous-traitance',
        'XQ':'Location, charges locatives et de copropriété',
        'YU':'Personnel extérieur à l’entreprise',
        'SS':'Rémunération d’intermédiaires et honoraires (hors rétrocessions)',
        'YV':'Rétrocessions d’honoraires, commissions et courtages',
        'ST':'Autres comptes',
        'ZI':'Total du poste correspondant à la ligne FW du tableau n° 2052',
        'YW':'Taxe professionnelle',
        '9Z':'Autres impôts, taxes et versements assimilés',
        'YX':'Total du compte correspondant à la ligne FX du tableau n° 2052',
        'YY':'Montant de la TVA. collectée',
        'YZ':'Total TVA. déductible sur biens et services',
        'YP':'Effectif moyen du personnel',
        'ZR':'Filiales et participations',
        }


    code_liasse_actif_simplifie = {
        '010':'Immobilisations incorporelles - Fonds commercial',
        '014':'Immobilisations incorporelles – Autres',
        '028':'Immobilisations corporelles',
        '040':'Immobilisations financières',
        '044':'Total Actif Immobilisé',
        '050':'Matières premières, approvisionnements, en cours de production',
        '060':'Stock marchandises',
        '064':'Avances et acomptes versés sur commandes',
        '068':'Créances – Clients et comptes rattachés',
        '072':'Créances – Autres',
        '080':'Valeurs mobilières de placement',
        '084':'Disponibilités',
        '088':'Caisse',
        '092':'Charges constatées d’avance',
        '096':'Total Actif circulant + Charges constatées d’avance',
        '110':'Total général Actif',
        '120':'Capital social ou individuel',
        '124':'Ecarts de réévaluation',
        '126':'Réserve légale',
        '130':'Réserves réglementées',
        '132':'Autres réserves',
        '134':'Report à nouveau',
        '136':'Résultat de l’exercice',
        '140':'Provisions réglementées',
        '142':'Total des capitaux propres - Total I',
        '154':'Provisions pour risques et charges - Total II',
        '156':'Emprunts et dettes assimilées',
        '164':'Avances et acomptes reçus sur commandes en cours',
        '166':'Fournisseurs et comptes rattachés',
        '169':'Autres dettes dont comptes courant d’associés de l’exercice N',
        '172':'Autres dettes',
        '174':'Produits constatés d’avance',
        '176':'Total des dettes',
        '180':'Total général Passif',
        '193':'Dont immobilisations financières à moins d’un an',
        '195':'Dont dettes à plus d’un an',
        '197':'Dont créances à plus d’un an',
        '182':'Coût de revient des immobilisations acquises ou créées au cours de l’exercice',
        '199':'Dont comptes courant d’associés débiteurs',
        '184':'Prix de vente hors T.V.A. des immobilisations cédées au cours de l’exercice'
        }

    code_liasse_CR_simplifie = {
        '209':'Ventes de marchandises – Export',
        '215':'Production vendue de biens - Export',
        '217':'Production vendue de services - Export',
        '210':'Ventes de marchandises – France',
        '214':'Production vendue de biens – France',
        '218':'Production vendue de services - France',
        '222':'Production stockée',
        '224':'Production immobilisée',
        '226':'Subventions d’exploitation reçues',
        '230':'Autres produits',
        '232':'Total des produits d’exploitation hors T.V.A.',
        '234':'Achats de marchandises (y compris droits de douane)',
        '236':'Variation de stock (marchandises)',
        '238':'Achats de matières premières et autres approvisionnements (y compris droits de',
        '240':'Variation de stock (matières premières et approvisionnement)',
        '24B':'(dont crédit bail mobilier)',
        '24A':'(dont crédit bail immobilier)',
        '242':'Autres charges externes.',
        '243':'(dont taxe professionnelle)',
        '244':'Impôts, taxes et versements assimilés',
        '250':'Rémunérations du personnel',
        '252':'Charges sociales',
        '254':'Dotations aux amortissements',
        '256':'Dotations aux provisions',
        '259':'(dont provisions fiscales pour implantations commerciales à l’étranger)',
        '262':'Autres charges',
        '264':'Total des charges d’exploitation',
        '270':'Résultat d’exploitation',
        '280':'Produits financiers',
        '290':'Produits exceptionnels',
        '294':'Charges financières',
        '300':'Charges exceptionnelles',
        '306':'Impôts sur les bénéfices',
        '310':'Bénéfice ou perte',
        '316':'Rémunération et avantages personnels non déductibles',
        '374':'Montant de la T.V.A. collectée',
        '376':'Effectif moyen du personnel',
        '378':'Montant de la T.V.A. déductible sur biens et services'
        }



    code_liasse_imm_amo_simplifie = {
        '402':'AUGMENTATIONS Immobilisations incorporelles – Fonds commercial',
        '404':'DIMINUTIONS Immobilisations incorporelles – Fonds commercial',
        '412':'AUGMENTATIONS Immobilisations incorporelles –Autres immobilisations',
        '414':'DIMINUTIONS Immobilisations incorporelles –Autres immobilisations incorporelles',
        '422':'AUGMENTATIONS Imm. corporelles – Terrains',
        '432':'AUGMENTATIONS Imm. corporelles – Constructions',
        '442':'AUGMENTATIONS Imm. corporelles – Installations techniques matériel et outillage',
        '452':'AUGMENTATIONS Imm. corporelles – Installations générales, agencements divers',
        '462':'AUGMENTATIONS Imm. corporelles – Matériel de transport',
        '472':'AUGMENTATIONS Imm. corporelles – Autres immobilisations corporelles',
        '482':'AUGMENTATIONS Immobilisations financières',
        '484':'DIMINUTIONS Immobilisations financières',
        '490':'Total Immobilisations (Valeur brute)',
        '492':'Total Immobilisations (Augmentations)',
        '494':'Total Immobilisations (Diminutions)',
        '582':'Total Plus-values, Moins-values (Valeur résiduelle)',
        '584':'Total Plus-values, Moins-values (Prix de cession)',
        '585':'Total Immobilisations – Amortissement - Plus-values, Moins-values (Long terme -',
        '596':'Total Immobilisations – Amortissement - Plus-values, Moins-values (Court terme)',
        '597':'Total Immobilisations – Amortissement - Plus-values, Moins-values (Long terme -',
        '599':'Total Immobilisations – Amortissement - Plus-values, Moins-values (Long terme -',
        
        
        '602':'AUGMENTATIONS Provisions réglementées – Amortissements dérogatoires',
        '603':'AUGMENTATIONS Provisions réglementées – Dont majorations exceptionnelles de',
        '612':'AUGMENTATIONS Provisions réglementées – Autres provisions réglementées',
        '622':'AUGMENTATIONS Provisions pour risques et charges',
        '632':'AUGMENTATIONS Provisions pour dépréciation – Sur immobilisations',
        '642':'AUGMENTATIONS Provisions pour dépréciation – Sur stocks et en cours',
        '652':'AUGMENTATIONS Provisions pour dépréciation – Sur clients et comptes rattachés',
        '662':'AUGMENTATIONS Provisions pour dépréciation – Autres provisions pour',
        '682':'AUGMENTATIONS Total Relevé des provisions',
        '604':'DIMINUTIONS Provisions réglementées – Amortissements dérogatoires',
        '605':'DIMINUTIONS Provisions réglementées – Dont majorations exceptionnelles de 30%',
        '614':'DIMINUTIONS Provisions réglementées – Autres provisions réglementées',
        '624':'DIMINUTIONS Provisions pour risques et charges',
        '634':'DIMINUTIONS Provisions pour dépréciation – Sur immobilisations',
        '644':'DIMINUTIONS Provisions pour dépréciation – Sur stocks et en cours',
        '654':'DIMINUTIONS Provisions pour dépréciation – Sur clients et comptes rattachés',
        '664':'DIMINUTIONS Provisions pour dépréciation – Autres provisions pour dépréciation',
        '684':'DIMINUTIONS Total Relevé des provisions',
        '374':'DIVERS Montant de la TVA collectée',
        '378':'DIVERS Montant de la TVA déductible sur biens et services (sauf immobilisations)',
        
        '376' : 'Effectif moyens du personnel',
        }

    code_liasse_actif_consolide = {
        'AA':'Capital souscrit non appelé',
        'AB':'Frais d’établissement',
        'CX':'Frais de développement ou de recherche et développement',
        'AF':'Concessions, brevets et droits similaires',
        'AH':'Fonds commercial',
        'AJ':'Fonds commercial',
        'AL':'Avances et acomptes sur immobilisations incorporelles.',
        'A1':'Ecarts d’acquisition',
        'A2':'Sur valeurs - goodwill',
        'A3':'Différence de première consolidation',
        'AN':'Terrains',
        'AP':'Constructions',
        'AR':'Installations techniques, matériel et outillage industriels',
        'AT':'Autres immobilisations corporelles',
        'AV':'Immobilisations en cours',
        'AX':'Avances et acomptes',
        'CS':'Participations évaluées - mise en équivalence',
        'CU':'Autres participations',
        'BB':'Créances rattachées à des participations',
        'BD':'Autres titres immobilisés',
        'BF':'Prêts',
        'BH':'Autres immobilisations financières',
        'A4':'Titres mis en équivalence',
        'BJ':'TOTAL (I)',
        'BL':'Matières premières, approvisionnements',
        'BN':'En cours de production de biens',
        'BP':'En cours de production de services',
        'BR':'Produits intermédiaires et finis',
        'BT':'Marchandises',
        'BV':'Avances et acomptes versés sur commandes',
        'BX':'Clients et comptes rattachés',
        'BZ':'Autres créances',
        'CB':'Capital souscrit et appelé, non versé',
        'CD':'Valeurs mobilières de placement',
        'CF':'Disponibilités',
        'CH':'Charges constatées d’avance',
        'CJ':'TOTAL (II)',
        'CW':'Charges à répartir ou frais d’émission d’emprunt',
        'CM':'Primes de remboursement des obligations (IV)',
        'CN':'Ecarts de conversion actif (V)',
        'CO':'TOTAL GENERAL (0 à V)',
        'CP':'Parts à moins d’un an',
        'CR':'Parts à plus d’un an'
        }

    code_liasse_passif_consolide = {
        'DA':'Capital social ou individuel',
        'DB':'Primes d’émission, de fusion, d’apport, ...',
        'EK':'(dont écart d’équivalence)',
        'DC':'Ecarts de réévaluation',
        'DD':'Réserve légale (1)',
        'DE':'Réserves statutaires ou contractuelles',
        'DF':'Réserves réglementées (1)',
        'DG':'Autres réserves',
        'DH':'Report à nouveau',
        'P1':'Ecarts de conversion',
        'P2':'Résultat consolidé part du groupe',
        'DJ':'Subventions d’investissement',
        'DK':'Provisions réglementées',
        'DL':'TOTAL (I)',
        'DM':'Produit des émissions de titres participatifs',
        'DN':'Avances conditionnées',
        'P3':'Autres',
        'DO':'TOTAL (II)',
        'P4':'Ecarts de conversion',
        'P5':'Dans les réserves',
        'P6':'Dans les résultats',
        'P7':'TOTAL (III)',
        'P8':'Impôts différés',
        'P9':'Ecarts d’acquisition',
        'DP':'Provisions pour risques',
        'DQ':'Provisions pour charges',
        'DR':'TOTAL (IV)',
        'DS':'Emprunts obligataires convertibles',
        'DT':'Autres emprunts obligataires',
        'DU':'Emprunts et dettes auprès des établissements de crédit (3)',
        'DV':'Emprunts et dettes financières divers (4)',
        'DW':'Avances et acomptes reçus sur commandes en cours',
        'DX':'Dettes fournisseurs et comptes rattachés',
        'DY':'Dettes fiscales et sociales',
        'DZ':'Dettes sur immobilisations et comptes rattachés',
        'EA':'Autres dettes',
        'EB':'Produits constatés d’avance (2)',
        'EC':'TOTAL (IV)',
        'ED':'(V)',
        'EE':'TOTAL GENERAL (I à V)',
        'EF':'Dont réserve réglementée des plus-values à long terme',
        'EG':'Dettes et produits constatés d’avance à moins d’un an',
        'EH':'Dont concours bancaires courants, et soldes créditeurs de banques et C.C.P.',
        'EI':'Dont emprunts participatifs'
        }

    code_liasse_CR_consolide = {
        'FA':'Ventes de marchandises',
        'FD':'Production vendue biens',
        'FG':'Production vendue services',
        'FJ':'Chiffres d’affaires nets',
        'FM':'Production stockée',
        'FN':'Production immobilisée',
        'FO':'Subventions d’exploitation',
        'FP':'Reprises sur amortissements et provisions, transfert de charges',
        'FQ':'Autres produits',
        'FR':'Total des produits d’exploitation (I)',
        'FS':'Achats de marchandises (y compris droits de douane)',
        'FT':'Variation de stock (marchandises)',
        'FU':'Achats de matières premières et autres approvisionnements',
        'FV':'Variation de stock (matières premières et approvisionnements)',
        'FW':'Autres achats et charges externes',
        'FX':'Impôts, taxes et versements assimilés',
        'FY':'Salaires et traitements',
        'FZ':'Charges sociales',
        'GA':'Dot. d’exploit. - Dotations aux amortissements',
        'GB':'Dot. d’exploit. - Dotations aux provisions',
        'GC':'Dot. d’exploit. Sur actif circulant : dotations aux provisions',
        'GD':'Dot. d’exploit. Pour risques et charges : dotations aux provisions',
        'GE':'Autres charges',
        'GF':'Total des charges d’exploitation (II)',
        'GG':'- RESULTAT D’EXPLOITATION (I - II)',
        'GH':'Bénéfice attribué ou perte transférée (III)',
        'GI':'Perte supportée ou bénéfice transféré (IV)',
        'GJ':'Produits financiers de participations',
        'GK':'Produits des autres valeurs mobilières et créances de l’actif immobilisé',
        'GL':'Autres intérêts et produits assimilés',
        'GM':'Reprises sur provisions et transferts de charges',
        'GN':'Différences positives de change',
        'GO':'Produits nets sur cessions de valeurs mobilières de placement',
        'GP':'Total des produits financiers (V)',
        'GQ':'Dotations financières sur amortissements et provisions',
        'GR':'Intérêts et charges assimilées',
        'GS':'Différences négatives de change',
        'GT':'Charges nettes sur cessions de valeurs mobilières de placement',
        'GU':'Total des charges financières (VI)',
        'GV':'- RESULTAT FINANCIER (V - VI)',
        'GW':'- RESULTAT COURANT AVANT IMPOTS (I - II + III - IV + V - VI)',
        'HA':'Produits exceptionnels sur opérations de gestion',
        'HB':'Produits exceptionnels sur opérations en capital',
        'HC':'Reprises sur provisions et transferts de charges',
        'HD':'Total des produits exceptionnels (VII)',
        'HE':'Charges exceptionnelles sur opérations de gestion',
        'HF':'Charges exceptionnelles sur opérations en capital',
        'HG':'Dotations exceptionnelles aux amortissements et provisions',
        'HH':'Total des charges exceptionnelles (VIII)',
        'HI':'- RESULTAT EXCEPTIONNEL (VII - VIII)',
        'HJ':'Participation des salariés aux résultats de l’entreprise',
        'HK':'Impôts sur les bénéfices',
        'R1':'Impôts différés',
        'R2':'- RESULTAT NET AVANT AMORTISSEMENT DES ECARTS D’ACQUISITION',
        'R3':'Dotation aux amortissements des écarts d’acquisition',
        'R4':'Résultat net des sociétés mises en équivalence',
        'R5':'Résultat net des entreprises intégrées',
        'R6':'Résultat Groupe (Résultat net consolidé)',
        'R7':'Part des intérêts minoritaires (Résultat hors groupe)',
        'R8':'Résultat net part du groupe (part de la société mère)',
        'HP':'Renvois : Crédit-bail mobilier',
        'HQ':'Renvois : Crédit-bail immobilier'
        
        
        }


    code_liasse_CA_banques = {
        'A1':'ACTIF - Créances sur les Ets de crédit',
        'A2':'ACTIF - Créances sur la clientèle',
        'A3':'TOTAL ACTIF',
        'P1':'PASSIF - Dettes envers les Ets de crédit',
        'P2':'PASSIF - Comptes créditeurs à la clientèle',
        'P3':'PASSIF - Capital souscrit',
        'P4':'PASSIF - Primes d’émission',
        'P5':'PASSIF - Réserves',
        'P6':'PASSIF - Ecarts de réévaluation',
        'P7':'PASSIF - Report à nouveau',
        'P8':'PASSIF - Résultat de l’exercice',
        'P9':'TOTAL PASSIF',
        'R1':'Compte de résultat - Intérêts et produits assimilés',
        'R2':'Compte de résultat - Intérêts et charges assimilées',
        'R3':'Compte de résultat - Résultat de l’exercice'
        }

    code_liasse_CA_banques = {
        'A1':'ACTIF - Placements',
        'A2':'TOTAL ACTIF',
        'P1':'PASSIF - Capitaux propres',
        'P2':'PASSIF - Provisions techniques brutes',
        'P3':'TOTAL PASSIF',
        'R1':'Compte de résultat - Primes - Cotisations acquises',
        'R2':'Compte de résultat - Charges des sinistres',
        'R3':'Compte de résultat - Résultat technique',
        'R4':'Compte de résultat - Résultat de l’exercice'
        }

    code_greffe = {
        '4701':'AGEN',
        '1301':'AIX EN PROVENCE',
        '2001':'AJACCIO',
        '8101':'ALBI',
        '6101':'ALENCON',
        '8002':'AMIENS',
        '4901':'ANGERS',
        '1601':'ANGOULEME',
        '7401':'ANNECY',
        '0601':'ANTIBES',
        '6201':'ARRAS',
        '0702':'AUBENAS',
        '3201':'AUCH',
        '1501':'AURILLAC',
        '8901':'AUXERRE',
        '8401':'AVIGNON',
        '5501':'BAR LE DUC',
        '2002':'BASTIA',
        '6401':'BAYONNE',
        '6001':'BEAUVAIS',
        '9001':'BELFORT',
        '2401':'BERGERAC',
        '2701':'BERNAY',
        '2501':'BESANCON',
        '3402':'BEZIERS',
        '4101':'BLOIS',
        '9301':'BOBIGNY',
        '3302':'BORDEAUX',
        '6202':'BOULOGNE SUR MER',
        '0101':'BOURG EN BRESSE',
        '1801':'BOURGES',
        '2901':'BREST',
        '5401':'BRIEY',
        '1901':'BRIVE',
        '1402':'CAEN',
        '4601':'CAHORS',
        '0602':'CANNES',
        '1101':'CARCASSONNE',
        '8102':'CASTRES',
        '7102':'CHALON SUR SAONE',
        '5101':'CHALONS SUR MARNE',
        '7301':'CHAMBERY',
        '2801':'CHARTRES',
        '3601':'CHATEAUROUX',
        '5201':'CHAUMONT',
        '5001':'CHERBOURG',
        '6303':'CLERMONT FERRAND',
        '6002':'COMPIEGNE',
        '7801':'CORBEIL',
        '5002':'COUTANCES',
        '9401':'CRETEIL',
        '0301':'CUSSET',
        '4001':'DAX',
        '7601':'DIEPPE',
        '2104':'DIJON',
        '5952':'DOUAI',
        '8302':'DRAGUIGNAN',
        '5902':'DUNKERQUE',
        '8801':'EPINAL',
        '2702':'EVREUX',
        '0901':'FOIX',
        '8303':'FREJUS',
        '0501':'GAP',
        '0603':'GRASSE',
        '7001':'GRAY',
        '3801':'GRENOBLE',
        '2301':'GUERET',
        '8501':'LA ROCHE SUR YON',
        '1704':'LA ROCHELLE',
        '5301':'LAVAL',
        '7606':'LE HAVRE',
        '7202':'LE MANS',
        '4302':'LE PUY',
        '3303':'LIBOURNE',
        '5910':'LILLE METROPOLE',
        '8701':'LIMOGES',
        '1407':'LISIEUX',
        '3902':'LONS LE SAUNIER',
        '5601':'LORIENT',
        '6901':'LYON',
        '7106':'MACON',
        '0401':'MANOSQUE',
        '1303':'MARSEILLE',
        '7701':'MEAUX',
        '7702':'MELUN',
        '4801':'MENDE',
        '4002':'MONT DE MARSAN',
        '8201':'MONTAUBAN',
        '0303':'MONTLUCON',
        '3405':'MONTPELLIER',
        '5402':'NANCY',
        '9201':'NANTERRE',
        '4401':'NANTES',
        '1104':'NARBONNE',
        '5802':'NEVERS',
        '0605':'NICE',
        '3003':'NIMES',
        '7901':'NIORT',
        '4502':'ORLEANS',
        '7501':'PARIS',
        '6403':'PAU',
        '2402':'PERIGUEUX',
        '6601':'PERPIGNAN',
        '8602':'POITIERS',
        '7802':'PONTOISE',
        '2903':'QUIMPER',
        '5103':'REIMS',
        '3501':'RENNES',
        '4201':'ROANNE',
        '1203':'RODEZ',
        '2602':'ROMANS',
        '7608':'ROUEN',
        '2202':'SAINT BRIEUC',
        '4202':'SAINT ETIENNE',
        '3502':'SAINT MALO',
        '4402':'SAINT NAZAIRE',
        '0202':'SAINT QUENTIN',
        '1708':'SAINTES',
        '1304':'SALON',
        '0802':'SEDAN',
        '8903':'SENS',
        '0203':'SOISSONS',
        '1305':'TARASCON',
        '6502':'TARBES',
        '7402':'THONON LES BAINS',
        '8305':'TOULON',
        '3102':'TOULOUSE',
        '3701':'TOURS',
        '1001':'TROYES',
        '5906':'VALENCIENNES',
        '5602':'VANNES',
        '7803':'VERSAILLES',
        '3802':'VIENNE',
        '6903':'VILLEFRANCHE SUR SAONE',
        '6851':'COLMAR',
        '5751':'METZ',
        '6852':'MULHOUSE',
        '5752':'SARREGUEMINES',
        '6751':'SAVERNE',
        '6752':'STRASBOURG',
        '5753':'THIONVILLE',
        '9711':'BASSE TERRE',
        '9731':'CAYENNE',
        '9721':'FORT DE FRANCE',
        '9761':'MAMOUDZOU',
        '9712':'POINTE A PITRE',
        '9741':'ST DENIS DE LA REUNION',
        '9742':'ST PIERRE DE LA REUNION'
        }



    code_saisie = {
        '0':'Comptes annuels saisis sans anomalie',
        '1':'Comptes annuels saisis avec des incohérences comptables à la source du document',
        '1A':'Comptes annuels saisis avec des données manquantes à la source du document',
        '2':'Comptes annuels non saisis - Actif, Passif ou Compte de Résultat nul',
        '3':'Comptes annuels non saisis - Incomplets (des pages manquent)',
        '4':'Comptes annuels non saisis - Non détaillés (uniquement totaux et sous totaux)',
        '5':'Comptes annuels non saisis - Reçus en double exemplaire (doublon « informatique »)',
        '6':'Comptes annuels non saisis - Reçus en double exemplaire (bilan «rescanné »)',
        '7':'Comptes annuels non saisis - Comptes intermédiaires, situation provisoire',
        '8':'Comptes annuels non saisis - Illisibles, présentant un cadre gris très foncé (cadre "totaux")',
        '9':'Comptes annuels non saisis - Illisibles, manuscrits',
        '10':'Comptes annuels non saisis - Illisibles, présentant des caractères trop gras',
        '11':'Comptes annuels non saisis - Illisibles, scannés en biais ou présentant des pages rognées',
        '12':'Comptes annuels non saisis - Illisibles, numérisés trop clairement',
        '13':'Comptes annuels non saisis - Autres motifs d''illisibilité',
        '14':'Comptes annuels non saisis - Date d''exercice trop ancienne (+ de 5 ans)',
        '15':'Comptes annuels non saisis - Bilan de clôture de liquidation',
        '16':'Document non saisi - Ordonnance de Report d’Assemblée générale',
        '17':'Document non saisi - Refus du Tribunal de Commerce du Report de l''Assemblée générale',
        '18':'Document non saisi - Déclaration d’impôts',
        '19':'Document non saisi - Document autre que constitutif des comptes annuels',
        '20':'Document non saisi - Société immobilière',
        '21':'Document non saisi - Société étrangère',
        '22':'Comptes annuels non saisis - Déclaration de confidentialité incohérente',
        '23':'Comptes annuels non saisis – Mélange de documents'
        }

    code_type_bilan = {
        'C':'Complet',
        'S':'Simplifié',
        'K':'Consolidé',
        'B':'Banque',
        'A':'Assurance',
        }

    code_confidentialite={
        '0':'comptes annuels non confidentiels',
        '1':'comptes annuels confidentiels',
        '2':'compte de résultat confidentiel'
        }

    


